import { Stack } from '../src/stack'

describe('stack', () => {
  it('stack', () => {
    let s = new Stack()
    s.push(1)
    s.push(2)
    s.push(3)
    s.push(4)
    expect(s.toArray()).toEqual([1, 2, 3, 4])
    expect(s.pop()).toBe(4)
    expect(s.pop()).toBe(3)
    expect(s.peek()).toBe(2)
    expect(s.isEmpty()).toBeFalsy()
    s.clear()
    expect(s.size()).toBe(0)
  })
  test('stack capacity', () => {
    let stack = new Stack()
    expect(Number.isFinite(stack.capacity)).toBeFalsy()
    stack = new Stack(4)
    expect(Number.isFinite(stack.capacity)).toBeTruthy()
    expect(stack.capacity).toBe(4)
    // stack.capacity = 6
    // expect(stack.capacity).toBe(4)
    stack.push(1)
    stack.push(1)
    expect(stack.isFull()).toBeFalsy()
    stack.push(1)
    stack.push(1)
    stack.push(3)
    expect(stack.push(3)).toEqual(new Error('has full'))
    expect(stack.toArray()).toEqual([1,1,1,1])
    expect(stack.isFull()).toBeTruthy()
  })
})
